Repository dugsiiyeinc/photo-agency-site, pull requests merged in 2025-05, with the labels that each got.

#10 ADD HEADER SECTION
  index.html
  style.css
Labels: enhancement

#11 Add hero Section
  index.html
  style.css
Labels: enhancement

#12 Update Hero section as a Responsive
  style.css
Labels: enhancement

#13 Add Some Javascript as navigation fuctionality
  index.html
Labels: enhancement

#15 Add About Section With Responsive Design
  index.html
  style.css
Labels: enhancement

#16 Add Service Section With responsive Design
  index.html
  style.css
Labels: enhancement

#17 Add client Section With Responsive Design
  index.html
  style.css
Labels: enhancement

#19 🛠️ UPDATE Testimonial Section HTML & CSS
  index.html
  style.css
Labels: documentation

#22 UPDATE HTML STRUCTURE
  index.html
Labels: documentation

#25 add pricing-section
  index.html
  style.css
Labels: enhancement

#26 add Blog-section
  index.html
  style.css
Labels: enhancement

#28 add Footer
  index.html
  style.css
Labels: enhancement

#30 config-links
  index.html
Labels: help wanted

#32 config-navigation style
  style.css
Labels: documentation

#34 Improve Blog hover like zoom-in image and title color
  index.html
  style.css
Labels: documentation

#35 Create README.md
  README.md
Labels: enhancement

#37 Update contact section: modify info and layout for improved clarity
  index.html
  style.css
Labels: enhancement, ui or design

#38 Update Footer Logo and style
  index.html
  style.css
Labels: documentation

#39 add price
  index.html
Labels: documentation

#40 Update subtitle in about section
  index.html
Labels: documentation

#42 Add screenshots section to README
  README.md
  screenshots/About Section.PNG
  screenshots/Blog.PNG
  screenshots/Clients.PNG
  screenshots/Contact.PNG
  screenshots/Footer.PNG
  screenshots/Home Page.PNG
  screenshots/Pricing.PNG
  screenshots/Service.PNG
  screenshots/Testimonial.PNG
Labels: documentation

#52 feat: add blog page
  blog.html
Labels: enhancement

#55 Configbg
  style.css
Labels: enhancement
